FROM alpine:3.11

ENV WIENROOT=/wien2k
ENV PATH=$PATH:/wien2k

RUN mkdir /wien2k

COPY WIEN2k_19.1.tar /wien2k
COPY expand_lapw_inputs /wien2k
COPY siteconfig_lapw_inputs /wien2k
COPY w2web_inputs /wien2k

RUN apk update \
  && apk add make gcc gfortran tcsh expect libc-dev libstdc++ perl \
  && cd /wien2k \
  && tar -xvf WIEN2k_19.1.tar \
  && gunzip *.gz \
  && chmod +x expand_lapw \
  && ./expand_lapw < expand_lapw_inputs \
  && ./siteconfig_lapw < siteconfig_lapw_inputs \
  && w2web < w2web_inputs
